name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PDM
        run: pipx install pdm

      - name: Install dependencies
        run: pdm install -G test

      - name: Run tests with coverage
        run: pdm run pytest --cov=src/vibedir --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml